# Generated by Django 2.2.2 on 2020-06-16 18:30

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Nombre')),
                ('current_card', models.CharField(blank=True, max_length=999, null=True, verbose_name='Carta Actual')),
                ('white_cards', core.utils.ListField(blank=True, null=True, token=',', verbose_name='Cartas Blancas')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.CharField(default='M4ELEJ', max_length=6, primary_key=True, serialize=False, verbose_name='Código')),
                ('black_card', models.CharField(blank=True, max_length=999, null=True, verbose_name='Carta Negra')),
                ('is_active', models.BooleanField(default=False, verbose_name='Juego Iniciado')),
                ('players', models.ManyToManyField(blank=True, to='core.Player', verbose_name='Jugadores')),
            ],
            options={
                'verbose_name': 'Tabla de Juego',
                'verbose_name_plural': 'Tablas de Juego',
            },
        ),
    ]
